all: C2F negate ft2in mulByShift swap

C2F: C2F.s
	gcc $@.s -g -o $@

negate: negate.s
	gcc $@.s -g -o $@

ft2in: ft2in.s
	gcc $@.s -g -o $@

mulByShift: mulByShift.s
	gcc $@.s -g -o $@

swap: swap.s
	gcc $@.s -g -o $@
