all: C2F F2C negate ft2in in2ft mulByShift swap

C2F: C2F.s
	gcc $@.s -g -o $@

F2C: F2C.s
	gcc $@.s -g -o $@

negate: negate.s
	gcc $@.s -g -o $@

ft2in: ft2in.s
	gcc $@.s -g -o $@

in2ft: in2ft.s
	gcc $@.s -g -o $@

mulByShift: mulByShift.s
	gcc $@.s -g -o $@

swap: swap.s
	gcc $@.s -g -o $@
