all:	a hello readInt age readFloat quotes
a:	a.s
	gcc a.s -g -o a
	./a

hello:	hello.s
	gcc hello.s -g -o hello
	./hello

readInt: readInt.s
	gcc readInt.s -g -o readInt
	./readInt

age: age.s
	gcc age.s -g -o age
	./age

readFloat: readFloat.s
	gcc readFloat.s -g -o readFloat

quotes: quotes.s
	gcc quotes.s -g -o quotes
