all: addSubtract multiply divide otherMultiply changeCase eorExample movExample shiftExample

addSubtract: addSubtract.s
	gcc $@.s -g -o $@ 

multiply: multiply.s
	gcc $@.s -g -o $@

otherMultiply: otherMultiply.s
	gcc $@.s -g -o $@

divide: divide.s
	gcc $@.s -g -o $@

changeCase: changeCase.s
	gcc $@.s -g -o $@

eorExample: eorExample.s
	gcc $@.s -g -o $@

movExample: movExample.s
	gcc $@.s -g -o $@

shiftExample: shiftExample.s
	gcc $@.s -g -o $@

